name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-22.04
    container: cahirwpz/ii-so:latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code formatting
        run: ./run-clang-format.sh
      - name: Check for unauthorized modifications
        run: ./check-files.py
      - uses: education/autograding@v1
